title:              데이트, 취미, 커플 관련 APP 비교
email:              dmswo5677@gmail.com
description:        기계식 키보드의 펌웨어, 소규모 하드웨어의 이런 저런 기술적인 이야기를 전달하는 곳 입니다.
author:             박은재
baseurl:            "/"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

#이 밑으론 내가 추가
# Your disqus shortname, entering this will enable commenting on posts
disqus: pej12-github-pages

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-E35XH4JKP7
